name: CICD

on:
  push:
    branches:
      - release
  merge_group:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install rsync
        run: sudo apt-get install rsync -y

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
          run_install: true

      - name: pnpm i
        run: pnpm i

      - name: build
        run: npx craco build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: root
          SOURCE: /build
          TARGET: /www/temp
