name: CICD

on:
  push:
    branches:
      - release
  merge_group:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install rsync
        run: sudo apt-get install rsync -y
        
      - name: Install npm dependencies
        run: npm install --force
      - name: Run build task
        run: set process.env.CI=false && npx craco build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: root
          SOURCE: /build
          TARGET: /www/temp
